SELECT * FROM CITY;
SELECT * FROM VILLAGE;

--PART A
--1. Display all the villages of Rajkot city. 
	SELECT VILLAGE.NAME FROM VILLAGE 
	INNER JOIN CITY 
	ON VILLAGE.CITYID = CITY.CITYID;
--2. Display city along with their villages & pin code.
	SELECT CITY.NAME , VILLAGE.NAME , CITY.PINCODE FROM CITY 
	INNER JOIN VILLAGE 
	ON VILLAGE.CITYID = CITY.CITYID;
--3. Display the city having more than one village.
	SELECT CITY.NAME FROM CITY
	INNER JOIN VILLAGE 
	ON VILLAGE.CITYID = CITY.CITYID
	GROUP BY CITY.NAME
	HAVING COUNT(VILLAGE.CITYID) > 1;
--4. Display the city having no village.
	SELECT CITY.NAME FROM CITY 
	INNER JOIN VILLAGE ON VILLAGE.CITYID = CITY.CITYID
	WHERE VILLAGE.VID IS NULL;
--5. Count the total number of villages in each city.
	SELECT CITY.NAME , COUNT(VILLAGE.VID) FROM VILLAGE 
	INNER JOIN CITY
	ON VILLAGE.CITYID = CITY.CITYID
	GROUP BY CITY.NAME;
--6. Count the number of cities having more than one village.
	SELECT COUNT(CITY.CITYID) FROM CITY 
	WHERE CITY.CITYID IN (SELECT CITY.CITYID FROM VILLAGE INNER JOIN CITY
											ON VILLAGE.CITYID = CITY.CITYID GROUP BY CITY.CITYID
											HAVING COUNT(VILLAGE.CITYID) > 1);

	SELECT * FROM STU_MASTER;
--	4. Try to update SPI of Raju from 8.80 to 12.
	UPDATE STU_MASTER
	SET SPI = 12
	WHERE NAME = 'RAJU';
--5. Try to update Bklog of Neha from 0 to -1.
	UPDATE STU_MASTER
	SET BKLOG = -1
	WHERE NAME = 'NEHA';


--PART B
